### ISSUE TITLE
mysql_db and mysql_user tasks requires to set socket explicitely

### ISSUE THREAD

**Issue by themouette** [robertdebock/ansible-role-mysql#1]
**Describe the bug**
When running the role as is, I was unable to create databases or users.
The task always failed with the message

> unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, "Access denied for user 'root'@'localhost'")

**To Reproduce**
1. Run this role on ubuntu 18.04 with `mysql_users` and/or `mysql_databases` populated
2. See error

**Expected behavior**
Users and databases should be populated

**Error**
```
TASK [robertdebock.mysql : create users] *******************************************************************************************************************************************************************
failed: [owncloud.proxmox2018] (item={'name': 'nextcloud', 'password': 'nextcloud', 'priv': 'nextcloud.*:ALL', 'host': 'localhost'}) => {
    "changed": false,
    "item": {
        "host": "localhost",
        "name": "[redacted]",
        "password": "[redacted]",
        "priv": "[redacted].*:ALL"
    }
}

MSG:

unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, "Access denied for user 'root'@'localhost'")
```

**Environment**
- Control node OS: MacOs
- Control node Ansible version: 2.7.2
- Managed node OS: Ubuntu 18.04 LTS Bionic Beaver

**Additional context**
I fixed it locally by forcing `login_unix_socket: /var/run/mysqld/mysqld.sock` for both `mysql_user` and `mysql_db` tasks.

``` yml
- name: create databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
    encoding: "{{ item.encoding | default(omit) }}"
    collation: "{{ item.collation | default(omit) }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - "{{ mysql_databases }}"
  when:
    - mysql_databases is defined
    - ansible_virtualization_type != "docker"

- name: create users
  mysql_user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - "{{ mysql_users }}"
  when:
    - mysql_users is defined
    - ansible_virtualization_type != "docker"
```

**Comment by robertdebock** [comment]
Thanks for the feedback, I'll try to reproduce and fix.

**Comment by robertdebock** [comment]
I've tried to reproduce on Ubuntu using this code:
```
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    mysql_databases:
      - name: testdb
    mysql_users:
      - name: testuser
        password: testpass
        priv: "testdb.*:ALL"

  roles:
    - robertdebock.bootstrap
    - robertdebock.mysql
```

That seems to work:
```
[skipped]
TASK [robertdebock.mysql : create databases] ***********************************
changed: [ubuntu-1] => (item={u'name': u'testdb'})

TASK [robertdebock.mysql : create users] ***************************************
changed: [ubuntu-1] => (item={u'password': u'testpass', u'name': u'testuser', u'priv': u'testdb.*:ALL'})
```

And the user can also login:
```
vagrant@ubuntu1804:~$ mysql -u testuser -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 30
Server version: 10.1.34-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

@themouette can you paste your playbook in here? Including the variables for mysql_databases and mysql_users?
