### ISSUE TITLE
root password not set

### ISSUE THREAD

**Issue by thespacedoctor** [robertdebock/ansible-role-mysql#7]
## Describe the bug

Trying to install MySQL on Ubuntu 20.04. The `mysql_root_password` does not seem to be getting set. I can log into the mysql client from the unix root user as the mysql root user without a password.

## Playbook

```yaml
---
- name: Install MySQL - first time
  include_role:
    name: robertdebock.mysql
  vars:
    mysql_bind_address: 127.0.0.1
    mysql_pid: "/var/run/mysqld/mysqld.pid"
    mysql_socket: "/var/run/mysqld/mysqld.sock"
    mysql_root_password: "{{ lookup('file', '{{ playbook_dir }}/roles/install-mysql/files/mysql-root-password.txt') }}"
```

I also tried with a plaintext password and got the same issue.

## Environment

- Control node OS: MacOS 10.15.7
- Control node Ansible version: 2.9.1
- Managed node OS: Ubuntu 20.04
