### ISSUE TITLE
Wrong mariadb config path on Fedora 33

### ISSUE THREAD

**Issue by Obihoernchen** [robertdebock/ansible-role-mysql#9]
## Describe the bug

In Fedora 33 the path for mariadb config is `/etc/my.cnf`, not `/etc/mysql`, therefore config options like `bind-address` are ignored.

## Playbook

`requirements.yml`
```yaml
---
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.mysql

roles:
  - name: robertdebock.mysql
    version: 4.1.2
```

`playbook.yml`
```yaml
---
- name: Configure vserver
  hosts: vserver

  tasks:
    - include_role:
        name: robertdebock.mysql
```

`group_vars/vserver/mysql.yml`
```yaml
---
# The address mysql should bind to.
mysql_bind_address: 127.0.0.1

# The password to set for the root user. Also stored in my.cnf
mysql_root_password: "{{ vault_mysql_root_password }}"

# The buffer pool size.
mysql_innodb_buffer_pool_size: 4G

# The io capacity.
mysql_innodb_io_capacity: 2000
```

## Output

Config from Ansible role and actual config of runnig MariaDB server:
```
❯ grep bind /etc/mysql/mariadb.conf.d/50-server.cnf
bind-address = 127.0.0.1
❯ sudo ss -atp | grep mysql
LISTEN   0      80                           *:mysql                         *:*     users:(("mysqld",pid=906,fd=68))                                                                                                         
ESTAB    0      0                        [::1]:38282                     [::1]:mysql users:(("python",pid=3098,fd=6))                                                                                                         
ESTAB    0      0                        [::1]:mysql                     [::1]:38282 users:(("mysqld",pid=906,fd=96))                                                                                                         
```

Default Fedora 33 packages:
```
❯ rpm -ql mariadb-connector-c-config-3.1.12-1.fc33.noarch | grep ^/etc
/etc/my.cnf
/etc/my.cnf.d
/etc/my.cnf.d/client.cnf
❯ rpm -ql mariadb-server-10.4.18-1.fc33.x86_64 | grep ^/etc
/etc/logrotate.d/mariadb
/etc/my.cnf.d/enable_encryption.preset
/etc/my.cnf.d/mariadb-server.cnf
/etc/security/user_map.conf
❯ grep include /etc/my.cnf
# include all files from the config directory
!includedir /etc/my.cnf.d
```

## Environment

- Control node OS: Fedora 33 (Server Edition)
- Control node Ansible version: 2.9.18
- Managed node OS: Fedora 33 (Server Edition)
